id: AF956E6E6
title: Introductory verses
type: translation
source_metadata:
  languages:
  - bo
  datatype: PlainText
  created_at: 2022-03-01 22:08:52.423531
  last_modified_at: 2022-03-01 22:08:52.423539
